version: "3.9"
services:
  mysql-donations:
    container_name: mysql-donations
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: donations
  redis-donations:
    container_name: redis-donations
    image: redis
    ports:
      - 6379:6379
#  donations:
#    container_name: donations
#    image: donations
#    ports:
#      - 8080:8080
#    depends_on:
#      - mysql-donations
#      - redis-donations
#  balance:
#    container_name: balance
#    image: balance
#    ports:
#      - 8090:8090
#    depends_on:
#      - mysql-donations
#      - redis-donations
#      - donations
