server.servlet.context-path: /donations
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/donations
    username: root
    password: root
  jpa:
    database: MYSQL
    hibernate.ddl-auto: update
    show-sql: true