server.servlet.context-path: /donations
spring:
  profiles.active: test
  datasource:
    url: jdbc:mysql://localhost:3306/donations
    username: root
    password: root
  jpa:
    database: MYSQL
    hibernate.ddl-auto: update
    show-sql: true